### ISSUE TITLE
Automatic update of fontconfig

### ISSUE THREAD

**Issue by raffaem** [fontist/fontist#195]
Can `fontist install` be configured to automatically update `fontconfig` when a new font is installed?

Some software like LibreOffice rely on `fontconfig` to resolve fonts.

See my answer [here](https://askubuntu.com/a/1300747/176654).

**Comment by ronaldtse** [comment]
@raffaem thank you for the suggestion! I believe Fontist could trigger fontconfig on font installs. 

To do so perhaps we need to implement:
1. Detect whether fontconfig is installed
2. Install Fontist configuration for fontconfig, so that fontconfig reads the Fontist font directory
3. Fontist can trigger fc-cache/fc-match after a font is installed to make it available in fontconfig

Does this match your expectations?

**Comment by raffaem** [comment]
Yes, thanks :+1:

**Comment by ronaldtse** [comment]
Thanks @raffaem for the confirmation. We'll ping you once there is any update!
