### ISSUE TITLE
(URGENT) Unable to install Fontist fonts in GHA Ubuntu

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#236]
With the latest Fontist version there is an error of not being able to download files:

https://github.com/metanorma/mn-samples-iso/pull/72/checks?check_run_id=2345319579:
```
Downloading https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip...
331
Can't downloaded a file: /home/runner/.metanorma/fonts/source-fonts.zip (No such file or directory)
332
Can't unzip a file: /home/runner/.metanorma/fonts/source-fonts.zip (No such file or directory)
333
Can't find a font file: /home/runner/.metanorma/fonts/SourceSansPro-Regular.ttf
334
Can't find a font file: /home/runner/.metanorma/fonts/SourceSansPro-Bold.ttf
335
Can't find a font file: /home/runner/.metanorma/fonts/SourceSansPro-It.ttf
336
Can't find a font file: /home/runner/.metanorma/fonts/SourceSansPro-BoldIt.ttf
337
Can't find a font file: /home/runner/.metanorma/fonts/SourceSerifPro-Regular.ttf
338
Can't find a font file: /home/runner/.metanorma/fonts/SourceSerifPro-Bold.ttf
339
Can't find a font file: /home/runner/.metanorma/fonts/SourceSerifPro-It.ttf
340
Can't find a font file: /home/runner/.metanorma/fonts/SourceSerifPro-BoldIt.ttf
341
Can't find a font file: /home/runner/.metanorma/fonts/SourceCodePro-Regular.ttf
342
Can't find a font file: /home/runner/.metanorma/fonts/SourceCodePro-Bold.ttf
343
Can't find a font file: /home/runner/.metanorma/fonts/SourceCodePro-It.ttf
344
Can't find a font file: /home/runner/.metanorma/fonts/SourceCodePro-BoldIt.ttf
345
Can't find a font file: /home/runner/.metanorma/fonts/SourceSansPro-Light.ttf
346
Can't find a font file: /home/runner/.metanorma/fonts/SourceSansPro-LightIt.ttf
347
Can't find a font file: /home/runner/.metanorma/fonts/SourceHanSans-Normal.ttc
348
Can't find a font file: /home/runner/.metanorma/fonts/SourceHanSans-Bold.ttc
349
Can't find a font file: /home/runner/.metanorma/fonts/STIX2Math.otf
350
Downloading https://github.com/stipub/stixfonts/raw/master/archive/STIXv2.0.2/OTF/STIX2Math.otf...
351
```

**Comment by ronaldtse** [comment]
Maybe only on Linux, not macOS/Windows? 
https://github.com/metanorma/mn-samples-iso/issues/58#issuecomment-819960877

**Comment by alexeymorozov** [comment]
Found the following:

1. the mn2pdf java binary tries to download fonts because it misses the "--fonts-manifest" option (macos build fortunately seems to have the required fonts in system, so avoids this issue)
2. the option is missed because is was passed only since v1.4.7.1 but linux/macos builds use only v1.4.7
```
metanorma 1.4.7 from Metanorma installed
```
3. they use previous version because the build of v1.4.7.1 has been failed for linux and macos
- https://github.com/metanorma/packed-mn/runs/2328437620?check_suite_focus=true
- https://github.com/metanorma/packed-mn/runs/2328437728?check_suite_focus=true
4. which failed because of complex patches of the `FFI.ffi_lib` method, which involves `ffi-libarchive-binary` and `memfs`

It was fixed or almost fixed here https://github.com/metanorma/packed-mn/commit/0bdc5285ccc99772efd46d25a5146abd632af0df

May be it should be just released to fix the issue but I see [a failing build](https://github.com/metanorma/packed-mn/runs/2345205604) associated with this commit. Will discuss with Alex and investigate more.

**Comment by CAMOBAP** [comment]
@ronaldtse @alexeymorozov I think it's related to failure on the last release of packed-mn https://github.com/metanorma/packed-mn/actions. I'm investigating it right now

**Comment by alexeymorozov** [comment]
Finally all versions are fixed:

1. metanorma-snap for Linux is [released](https://github.com/metanorma/metanorma-snap/pull/16) as 1.4.7.2-1

`mn-samples-iso` has been successfully run with new releases: https://github.com/alexeymorozov/mn-samples-iso/runs/2528471649
