### ISSUE TITLE
Support HTTP/HTTPS proxies 

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#249]
In some organizations the corporate firewall blocks requests and requires usage of a corporate proxy. 

Fontist needs to support the HTTP_PROXY and HTTPS_PROXY environment variables so that it can support these. 

Required in: https://github.com/metanorma/metanorma/issues/202#issuecomment-880069380

**Comment by CAMOBAP** [comment]
@ronaldtse no extra work need because `HTTP_PROXY` supports out-of-the-box. Also we decided to leave it up-to user how to configure `git` to work with proxy

Also to be on the same page:
1. do we need to support it for case if `fontist` called as standalone command?
2. do we need to support SOCKS proxy if `fontist` called as standalone command?

I'm asking because if `fontist` called as part of `metanorma` it works

**Comment by ronaldtse** [comment]
> 1. do we need to support it for case if fontist called as standalone command?
> 2. do we need to support SOCKS proxy if fontist called as standalone command?

Yes.

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for answers I will proceed

**Comment by CAMOBAP** [comment]
Merged
