### ISSUE TITLE
Performance improvement?

### ISSUE THREAD

**Issue by opoudjis** [fontist/fontist#254]
This relates to the use of fontist in metanorma gem:

https://github.com/metanorma/metanorma/blob/main/lib/metanorma/fontist_utils.rb

`FontistUtils.install_fonts` in that gem is a wrapper for `Fontist::Manifest::Install`. Because `FontistUtils.install_fonts` in that routine was being run being once for each document compiled in a collection, as opposed to once for the entire collection, the slow execution of that method was having a cumulative effect. With 30-odd documents, it was adding up to a half an hour additional time.

I've eliminated that repeated reinstallation of fonts, but the time to execute `FontistUtils.install_fonts` in the `metanorma` gem is still a concern; in standalone document compilation mode it is certainly in the neighbourhood of at least 10 sec on my machine. Could you please review it for possible inefficiencies?

**Comment by ronaldtse** [comment]
I see only 3 lines relevant to `Fontist`, e.g.

https://github.com/metanorma/metanorma/blob/8c049f76d32797509a2c3acaec08cea5b073d914/lib/metanorma/fontist_utils.rb#L53

https://github.com/metanorma/metanorma/blob/8c049f76d32797509a2c3acaec08cea5b073d914/lib/metanorma/fontist_utils.rb#L59

https://github.com/metanorma/metanorma/blob/8c049f76d32797509a2c3acaec08cea5b073d914/lib/metanorma/fontist_utils.rb#L67

The rest of the lines seem quite simple. Maybe the culprit is somewhere here...

**Comment by alexeymorozov** [comment]
Released v1.11.3 🚀  Please try, it should be at least 10 times faster.

On my machine it speeded up from 13 sec to 700 ms (tested the Location command with our the most common manifest). It was done by avoiding repeated (1) searches for system fonts and (2) parsing of an index YAML during one call.

**Comment by opoudjis** [comment]
Confirmed, it's whizzing on all metanorma tests, other than "exit on not supported font after missing fontist index" (which is likely my own cleanup code).
