### ISSUE TITLE
SHA256 mismatch for PowerPointViewer.exe

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#99]
https://github.com/metanorma/mn-samples-nist/runs/913424201?check_suite_focus=true

```
/usr/local/bundle/gems/fontist-1.1.0/lib/fontist/utils/downloader.rb:15:in `download': The downloaded file from https://nchc.dl.sourceforge.net/project/mscorefonts2/cabs/PowerPointViewer.exe doesn't match with the expected sha256 checksum! (Fontist::Errors::TemparedFileError)
1483
	from /usr/local/bundle/gems/fontist-1.1.0/lib/fontist/utils/downloader.rb:25:in `download'
1484
	from /usr/local/bundle/gems/fontist-1.1.0/lib/fontist/font_formula.rb:108:in `download_file'
1485
	from /usr/local/bundle/gems/fontist-1.1.0/lib/fontist/utils/exe_extractor.rb:16:in `exe_extract'
1486
```

**Comment by ronaldtse** [comment]
Re-running to see if it still breaks.

**Comment by ronaldtse** [comment]
(and "Tampered" instead of "Tempered")

**Comment by ronaldtse** [comment]
Oh, it worked on a re-run. Strange!!

**Comment by ronaldtse** [comment]
The shasum 256 of that link is `c4e753548d3092ffd7dd3849105e0a26d9b5a1afe46e6e667fe7c6887893701f`, which is correctly provided in 
https://github.com/fontist/fontist/blob/7bb0857982477c72286c9bf21cb08bba4bdbb162/lib/fontist/formulas/cleartype_fonts.rb#L19

I wonder if there's an issue with SHA checking here, or is it because the file download failed?

**Comment by abunashir** [comment]
It is indeed strange, could be because of the download, but I think it should have thrown a different error then since [Tampered file error](https://github.com/fontist/fontist/blob/master/lib/fontist/utils/downloader.rb#L14) is explicitly set only when file download was complete and no other error was thrown by the underlying library.

Anyway, I've updated the typo and let me know if we see this kind of error again :)
